"""CAD / enclosure + routed wiring schematic generation.

Two artefacts from a hardware plan:

* :func:`openscad_enclosure` — a parametric, printable enclosure: a box sized to
  the board with wall thickness, lid, PCB standoffs, ventilation slots, and
  cutouts for the controls/ports present in the design. It is OpenSCAD source
  (render to STL in OpenSCAD) — we generate the model description, we do not
  claim an STL exists.
* :func:`wiring_schematic` — an SVG point-to-point wiring diagram: the
  controller on one side with labelled pins, each module as a box on the
  other, and routed orthogonal connectors colour-coded by bus (I²C, I²S, SPI,
  GPIO, power). This is a build aid, not an EDA schematic.

Honest: dimensions are sensible defaults/parametric — the engineer verifies
against the real board and module outlines before printing.
"""

from __future__ import annotations

from typing import Any

BUS_COLORS = {
    "i2c": "#b49cff", "i2s": "#46d6a0", "spi": "#7aa2ff",
    "pwm": "#ff808f", "gpio": "#e3b341", "power": "#ffb142",
    "uart": "#6bc8ff",
}


# ── OpenSCAD enclosure ───────────────────────────────────────────────────────

def openscad_enclosure(plan) -> str:
    bd = plan.board
    W, H = bd["width_mm"], bd["height_mm"]
    wall = 2.0
    margin = 6.0
    ext_w, ext_h = W + margin * 2, H + margin * 2
    case_h = 32.0
    cids = {c["cid"] for c in plan.components}
    cutouts: list[str] = []
    if "rotary_encoder" in cids or any(c["category"] == "mech" and "encoder" in c["name"].lower()
                                        for c in plan.components):
        cutouts.append('// volume/menu knob on the top face')
        cutouts.append('translate([%f, %f, 2]) cylinder(h=6, r=4.5, $fn=32);'
                       % (ext_w / 2, 4))
    if "ssd1306" in cids or "st7789" in cids:
        cutouts.append('// display window')
        cutouts.append('translate([%f, %f, -1]) cube([30, 14, 6]);' % (6, ext_h - 18))
    if "speaker_4ohm" in cids:
        cutouts.append('// speaker grille (holes)')
        cutouts.append('for (x=[-10:6:10]) for (y=[-10:6:10]) '
                       'translate([%f+x, %f+y, -1]) cylinder(h=4, r=1.6, $fn=16);'
                       % (ext_w - 18, ext_h / 2))
    cutouts.append('// USB / power cutout on the rear wall')
    cutouts.append('translate([-1, %f, 10]) rotate([90,0,0]) cube([10, 16, 4]);'
                   % (ext_h / 2 - 8))

    L: list[str] = []
    a = L.append
    a(f"// {plan.title} — parametric enclosure (OpenSCAD).")
    a("// Generated by Trishula Vishvakarma. Verify against real board/module")
    a("// outlines before printing; dimensions are sensible defaults.")
    a("$fn=48;")
    a(f"board_w={W};\nboard_h={H};\nwall={wall};\nmargin={margin};\ncase_h={case_h};")
    a("ext_w = board_w + margin*2; ext_h = board_h + margin*2;")
    a("")
    a("module base() {")
    a("  difference() {")
    a("    translate([0,0,0]) cube([ext_w, ext_h, case_h]);")
    a("    translate([wall, wall, wall]) cube([ext_w-2*wall, ext_h-2*wall, case_h]);")
    a("    // M2.5 PCB standoff posts at corners")
    a("    for (sx=[wall+3, ext_w-wall-3]) for (sy=[wall+3, ext_h-wall-3])")
    a("        translate([sx-2.5, sy-2.5, -1]) cylinder(h=case_h+2, r=2.6);")
    a("    // ventilation slots (bottom)")
    a("    for (i=[0:6]) translate([wall+4+i*12, -1, wall/2]) cube([6, wall+1, 2]);")
    a("  }")
    a("}")
    a("module lid() {")
    a("  difference() {")
    a("    translate([0,0,case_h]) cube([ext_w, ext_h, wall]);")
    for line in cutouts:
        a("    " + line)
    a("    // lid screw clearance")
    a("    for (sx=[wall+3, ext_w-wall-3]) for (sy=[wall+3, ext_h-wall-3])")
    a("        translate([sx-1.6, sy-1.6, case_h-1]) cylinder(h=wall+2, r=1.7);")
    a("  }")
    a("}")
    a("base();")
    a("color(\"SlateGray\") lid();")
    a("")
    a("// Render with OpenSCAD: File > Export > Export as STL.")
    a("// Suggested: PETG, 0.2mm layer, 3 walls, 20% infill.")
    return "\n".join(L) + "\n"


# ── Routed wiring schematic (SVG) ────────────────────────────────────────────

def wiring_schematic(plan) -> str:
    """Return SVG text for a left=controller, right=modules point-to-point."""
    conns = plan.wiring
    # group modules (targets) with the signals they need
    modules: dict[str, list[dict]] = {}
    for w in conns:
        modules.setdefault(w["target"], []).append(w)

    order = ["i2s", "i2c", "spi", "uart", "pwm", "gpio", "power"]
    mod_names = sorted(modules.keys(),
                       key=lambda n: (order.index(next((c["protocol"] for c in modules[n]
                                                       if c["protocol"] in order), "gpio")),
                                      n))
    # geometry
    mcu_x, mcu_w = 20, 150
    mod_x, mod_w = 470, 210
    top, row_h = 54, 46
    h = top + max(1, len(mod_names)) * row_h + 30
    w = mod_x + mod_w + 20

    out = ['<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d">'
           % (w, h, w, h),
           '<style>.t{font-family:var(--font,monospace);font-size:10px;fill:var(--fg,#ddd)}'
           '.ts{font-size:11px;font-weight:700}.tg{font-size:9px;fill:var(--fg3,#888)}</style>']
    # MCU box
    mcu_h = 26 + 12 * min(10, len([c for c in conns if c["protocol"] != "power"]))
    out.append(f'<rect x="{mcu_x}" y="{top-10}" width="{mcu_w}" height="{mcu_h}" rx="8" '
               'class="b-mcu" fill="var(--accent-dim,#222)" stroke="var(--accent,#5fd38d)"/>')
    out.append(f'<text x="{mcu_x+mcu_w/2}" y="{top+6}" text-anchor="middle" class="t ts">'
               f'{plan.platform["mcu"]}</text>')

    # module boxes + routes; each net is a <g class="net" data-net="SIGNAL"> so the
    # UI can highlight the whole net (wire + end labels) on hover.
    for i, name in enumerate(mod_names):
        cy = top + i * row_h
        pins = modules[name]
        out.append(f'<rect x="{mod_x}" y="{cy-14}" width="{mod_w}" height="34" rx="7" '
                   'fill="var(--bg3,#1a1e25)" stroke="var(--border2,#333)"/>')
        out.append(f'<text x="{mod_x+10}" y="{cy}" class="t ts">{_esc(_short(name,26))}</text>')
        out.append(f'<text x="{mod_x+10}" y="{cy+12}" class="t tg">{len(pins)} wires</text>')
        for j, c in enumerate(pins):
            color = BUS_COLORS.get(c["protocol"], "#888")
            net = _net_id(c["signal"])
            x1 = mcu_x + mcu_w
            x2 = mod_x
            midx = (x1 + x2) / 2
            out.append(f'<g class="net" data-net="{net}">')
            out.append(
                f'<path class="net-wire" d="M{x1} {cy-6} C {midx} {cy-6}, {midx} {cy-6}, {x2} {cy-6}" '
                f'fill="none" stroke="{color}" stroke-width="1.6" opacity="0.85"/>')
            out.append(f'<text class="net-lbl t tg" x="{x1+6}" y="{cy-9}" fill="{color}">{_esc(c["source_pin"])}</text>')
            out.append(f'<text class="net-lbl t tg" x="{x2-6}" y="{cy-9}" text-anchor="end" fill="{color}">{_esc(c["target_pin"])}</text>')
            out.append('</g>')

    # legend
    lx = mcu_x; ly = h - 14
    out.append(f'<text x="{lx}" y="{ly}" class="t tg">bus:</text>')
    lx += 34
    for proto, color in BUS_COLORS.items():
        if any(c["protocol"] == proto for c in conns):
            out.append(f'<line x1="{lx}" y1="{ly-4}" x2="{lx+16}" y2="{ly-4}" stroke="{color}" stroke-width="2"/>')
            out.append(f'<text x="{lx+20}" y="{ly}" class="t tg">{proto}</text>')
            lx += 70
    out.append('</svg>')
    return "\n".join(out)


def _esc(s: str) -> str:
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def _short(s: str, n: int) -> str:
    return s if len(s) <= n else s[: n - 1] + "…"


def _net_id(signal: str) -> str:
    """Stable, HTML-safe net key shared by all wires of one signal."""
    s = str(signal).lower().replace("→", "to").replace(" ", "_").replace("/", "_")
    return "".join(ch for ch in s if ch.isalnum() or ch in "_-")
