"""Generate bring-up firmware skeletons from a hardware plan.

Produces a **credible skeleton**, not a finished product: the correct pin
definitions (read from the plan's conflict-free allocation), bus/I²S/SPI
setup, per-device bring-up with library hints, and a self-test in ``setup()``.
Where real product logic belongs (a FLAC decoder, a flight controller) it
emits an honest ``TODO`` and names the library — it never pretends to have
written that code.

Two targets:

* ``arduino``  — ``.ino`` C++ using the common Arduino ecosystem libraries;
* ``micropython`` — ``.py`` using ``machine`` for the RP2040/ESP32 ports.

Pin numbers are parsed from the wiring table (``GP16``/``D2``/``A4``), so the
generated code matches the BOM/wiring exactly.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any


@dataclass
class FirmwareFile:
    filename: str
    language: str
    content: str

    def to_dict(self):
        return {"filename": self.filename, "language": self.language, "content": self.content}


def _pins(plan) -> dict[str, Any]:
    """Map signal name -> gpio (int where numeric) from the wiring table."""
    pins: dict[str, Any] = {}
    for w in plan.wiring:
        if w["protocol"] == "power":
            continue
        sig = w["signal"]
        m = re.search(r"\d+", str(w["source_pin"]))
        if not m:
            continue
        pins[sig] = int(m.group())
    return pins


def _cids(plan) -> set[str]:
    return {c["cid"] for c in plan.components}


def generate(plan, target: str = "arduino") -> FirmwareFile:
    cids = _cids(plan)
    pins = _pins(plan)
    if target == "micropython":
        return FirmwareFile(
            f"{_slug(plan.title)}.py", "python",
            _micropython(plan, cids, pins),
        )
    return FirmwareFile(
        f"{_slug(plan.title)}.ino", "cpp",
        _arduino(plan, cids, pins),
    )


def _slug(title: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "_", title).strip("_").lower()
    return s or "project"


def _p(pins: dict, *names) -> str:
    for n in names:
        if n in pins:
            return str(pins[n])
    return "-1"


# ── Arduino ──────────────────────────────────────────────────────────────────

def _arduino(plan, cids, p) -> str:
    plat = plan.platform_key
    is_esp = "esp32" in plat
    L: list[str] = []
    a = L.append
    a(f"// {plan.title} — bring-up skeleton")
    a(f"// Platform: {plan.platform['name']}. Generated by Trishula Vishvakarma.")
    a("// Pin numbers match the wiring/pin-map table exactly.")
    a("")
    # I2C
    if any("i2c" in c.get("protocols", []) for c in plan.components):
        a(f"#define PIN_SDA {_p(p,'SDA')}")
        a(f"#define PIN_SCL {_p(p,'SCL')}")
    # SPI
    if any("spi" in c.get("protocols", []) for c in plan.components):
        a(f"#define PIN_SCK  {_p(p,'SCK')}")
        a(f"#define PIN_MOSI {_p(p,'MOSI')}")
        a(f"#define PIN_MISO {_p(p,'MISO')}")
    if "CS_SD" in p:
        a(f"#define PIN_CS_SD {p['CS_SD']}")
    if "CS_RADIO" in p:
        a(f"#define PIN_CS_RADIO {p['CS_RADIO']}")
    # I2S audio
    if any(c in cids for c in ("max98357a", "pcm5102a")):
        a(f"#define I2S_BCLK {_p(p,'BCLK')}")
        a(f"#define I2S_LRC  {_p(p,'LRCLK')}")
        a(f"#define I2S_DOUT {_p(p,'DOUT→DIN')}")
    if "inmp441" in cids:
        a(f"#define I2S_DIN  {_p(p,'DOUT→DIN')}")
    # rotary
    if "rotary_encoder" in cids:
        a(f"#define ENC_CLK {_p(p,'ENC_CLK')}")
        a(f"#define ENC_DT  {_p(p,'ENC_DT')}")
        a(f"#define ENC_SW  {_p(p,'ENC_SW')}")
    # ultrasonic
    if "hc_sr04" in cids:
        a(f"#define HCSR04_TRIG {_p(p,'TRIG')}")
        a(f"#define HCSR04_ECHO {_p(p,'ECHO')}")
    # motors (PWM)
    motor_pins = [v for k, v in p.items() if k == "PWM"]
    a("")
    a("#include <Arduino.h>")
    if any("i2c" in c.get("protocols", []) for c in plan.components):
        a("#include <Wire.h>")
    a("")
    a("void setup() {")
    a("  Serial.begin(115200); delay(1500);")
    a('  Serial.println("' + _slug(plan.title) + ' bring-up");')
    if any("i2c" in c.get("protocols", []) for c in plan.components):
        if is_esp:
            a("  Wire.begin(PIN_SDA, PIN_SCL);")
        else:
            a("  Wire.begin();")
        a("  // I2C scan — confirm addresses (BME280 0x76, MPU6050 0x68, SSD1306 0x3C):")
        a("  for (uint8_t a_=1;a_<127;a_++){Wire.beginTransmission(a_);")
        a("    if(!Wire.endTransmission()) Serial.printf(\"i2c 0x%02X\\n\",a_);}")
    if "micro_sd" in cids:
        a("  // SD card (use SD.h / SdFat): SCK/MOSI/MISO above, CS = PIN_CS_SD")
        a("  // TODO: SD.begin(PIN_CS_SD); write+read a test file.")
    if any(c in cids for c in ("max98357a", "pcm5102a")):
        a("  // I2S audio out (use ESP32 I2S.h or RP2040 pico-i2s/AudioI2S libraries).")
        a("  // TODO: init I2S at 44.1kHz/16-bit and play a 1kHz tone to verify the amp.")
        a("  //       Product audio (FLAC decode) lives in your audio player library here.")
    if "inmp441" in cids:
        a("  // I2S MEMS mic in: configure I2S RX on I2S_BCLK/I2S_LRC/I2S_DIN.")
    if "rotary_encoder" in cids:
        a("  pinMode(ENC_CLK, INPUT_PULLUP); pinMode(ENC_DT, INPUT_PULLUP); pinMode(ENC_SW, INPUT_PULLUP);")
    if "hc_sr04" in cids:
        a("  pinMode(HCSR04_TRIG, OUTPUT); pinMode(HCSR04_ECHO, INPUT);")
    if "mpu6050" in cids:
        a("  // MPU6050: init Wire, wake register 0x6B=0, read accel/gyro; CALIBRATE level & gyro zero.")
    if "bmp390" in cids:
        a("  // BMP390 baro: read pressure/temperature for altitude; keep away from motor airflow.")
    if "nrf24l01" in cids:
        a("  // nRF24 (RF24.h): SPI above, CE to a free GPIO, CS = PIN_CS_RADIO; verify failsafe.")
    if "motor" in {c["category"] for c in plan.components}:
        a("  // Motors via DRV8833/H-bridge on PWM pins; bench-test WITHOUT props first:")
        a("  //   verify spin direction per motor and arming lockout before any flight.")
    a("}")
    a("")
    a("void loop() {")
    if "bme280" in cids:
        a("  // TODO: read BME280 temp/humidity/pressure, publish/log a sample.")
    if "mpu6050" in cids:
        a("  // TODO: read IMU, run attitude estimate / flight loop.")
    if "rotary_encoder" in cids:
        a("  // TODO: poll encoder edges for volume/track.")
    a("  delay(100);")
    a("}")
    return "\n".join(L) + "\n"


# ── MicroPython ──────────────────────────────────────────────────────────────

def _micropython(plan, cids, p) -> str:
    L: list[str] = []
    a = L.append
    a(f"# {plan.title} — MicroPython bring-up skeleton")
    a(f"# Platform: {plan.platform['name']}. Pins match the wiring table.")
    a("from machine import Pin, I2C, SPI, PWM")
    a("import time")
    a("")
    if any("i2c" in c.get("protocols", []) for c in plan.components):
        a(f"i2c = I2C(0, sda=Pin({_p(p,'SDA')}), scl=Pin({_p(p,'SCL')}), freq=400_000)")
        a("print('i2c devices:', [hex(x) for x in i2c.scan()])  # expect 0x76/0x68/0x3c …")
    if any("spi" in c.get("protocols", []) for c in plan.components):
        a(f"spi = SPI(0, baudrate=4_000_000, sck=Pin({_p(p,'SCK')}), "
          f"mosi=Pin({_p(p,'MOSI')}), miso=Pin({_p(p,'MISO')}))")
    if "CS_SD" in p:
        a(f"cs_sd = Pin({p['CS_SD']}, Pin.OUT, value=1)  # microSD (use sdcard.py + os.mount)")
    if "rotary_encoder" in cids:
        a(f"enc_clk = Pin({_p(p,'ENC_CLK')}, Pin.IN, Pin.PULL_UP)")
        a(f"enc_dt  = Pin({_p(p,'ENC_DT')}, Pin.IN, Pin.PULL_UP)")
        a(f"enc_sw  = Pin({_p(p,'ENC_SW')}, Pin.IN, Pin.PULL_UP)")
    if "hc_sr04" in cids:
        a(f"trig = Pin({_p(p,'TRIG')}, Pin.OUT)")
        a(f"echo = Pin({_p(p,'ECHO')}, Pin.IN)")
    if "motor" in {c["category"] for c in plan.components}:
        motor_pins = [str(v) for k, v in p.items() if k == "PWM"]
        pin_list = ", ".join(motor_pins) if motor_pins else "0"
        a("# motor driver PWMs (DRV8833) — bench-test without props:")
        a(f"motors = [PWM(Pin(n)) for n in ({pin_list})]")
        a("for m in motors:")
        a("    m.freq(20_000)")
        a("    m.duty_u16(0)")
    a("")
    a("def main():")
    if any(c in cids for c in ("max98357a", "pcm5102a")):
        a("    # TODO: I2S out via machine.I2S (RP2040/ESP32): BCLK/LRCLK/DOUT pins above;")
        a("    #       play a tone, then wire in your FLAC/decoder library for product audio.")
    if "bme280" in cids:
        a("    # TODO: read BME280 over i2c; log/publish samples.")
    if "mpu6050" in cids:
        a("    # TODO: init MPU6050 (wake 0x6B), calibrate, read accel/gyro.")
    a("    while True:")
    a("        time.sleep_ms(100)")
    a("")
    a('if __name__ == "__main__":')
    a("    main()")
    return "\n".join(L) + "\n"


def motor_pips(pins: list[str]) -> str:
    return ", ".join(pins) if pins else "0"
