"""Netlist construction, KiCad/CSV export, and design-rule checks.

Takes a :class:`~trishula.engineering.planner.HardwarePlan` and:

* collapses the wiring table into **nets** (a named signal and every pin on
  it), giving each part a reference designator from the BOM;
* exports to a **KiCad-like netlist** (the v1 ``.net``/Eeschema netlist
  shape) and a flat **CSV** — both are hand-off artefacts, not a full
  schematic (that is drawn in an EDA tool from this);
* runs **design-rule checks (DRC)**: I2C pull-ups, common ground, power-rail
  presence, duplicate net assignment, 5V/3.3V logic-level mismatches,
  decoupling present, and motor-load via a driver.

Everything is deterministic and honest: DRC returns warnings/errors with
clear guidance; it never silently "fixes" a design.
"""

from __future__ import annotations

import csv
import io
from dataclasses import dataclass, field, asdict
from typing import Any

# signals that are rails / shared buses and may legitimately touch many pins
RAIL_NET = {"3V3", "GND"}
SHARED_BUS_SIGNALS = {"SDA", "SCL", "SCK", "MOSI", "MISO", "BCLK", "LRCLK", "DOUT→DIN"}


@dataclass
class Net:
    name: str
    protocol: str
    pins: list[dict[str, str]] = field(default_factory=list)  # {ref, pin, part}

    def to_dict(self): return asdict(self)


def _ref_map(plan) -> dict[str, str]:
    """Map a part name (and short cid) to its reference designator."""
    ref_by_name: dict[str, str] = {}
    cid_by_name: dict[str, str] = {}
    # components carry cid; bom carries ref + name
    comp_name_to_cid = {c["name"]: c["cid"] for c in plan.components}
    for item in plan.bom:
        ref_by_name[item["name"]] = item["ref"]
        cid = comp_name_to_cid.get(item["name"])
        if cid:
            cid_by_name[cid] = item["ref"]
    return {**ref_by_name, **{k + "_cid": v for k, v in cid_by_name.items()}}


def build_nets(plan) -> list[Net]:
    nets: dict[str, Net] = {}
    for w in plan.wiring:
        name = w["signal"]
        # normalize power rails
        if w["protocol"] == "power" and name in ("3V3", "GND"):
            net_name = name
        else:
            net_name = name
        if net_name not in nets:
            nets[net_name] = Net(net_name, w["protocol"])
        nets[net_name].pins.append({
            "ref": "MCU",
            "pin": str(w["source_pin"]),
            "part": plan.platform.get("mcu", "MCU"),
        })
        nets[net_name].pins.append({
            "ref": w["target"],
            "pin": str(w["target_pin"]),
            "part": w["target"],
        })
    return list(nets.values())


def net_names(plan) -> list[str]:
    return [n.name for n in build_nets(plan)]


# ── exports ──────────────────────────────────────────────────────────────────

def export_csv(plan) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["net", "protocol", "ref", "pin", "part"])
    for net in build_nets(plan):
        for pin in net.pins:
            w.writerow([net.name, net.protocol, pin["ref"], pin["pin"], pin["part"]])
    return buf.getvalue()


def export_kicad_netlist(plan) -> str:
    """Emit a KiCad-style netlist (Eeschema ``.net``) skeleton.

    Components and nets are listed so it can be imported/reconciled in a CAD
    tool; footprints are left to the designer (honest — we don't invent
    library paths).
    """
    lines: list[str] = []
    a = lines.append
    a('(export (version "(D)")')
    a('  (design')
    a(f'    (source "{plan.title} — generated by Trishula Vishvakarma")')
    a('  )')
    a('  (components')
    # MCU
    a(f'    (comp (ref "MCU")')
    a(f'      (value "{plan.platform["mcu"]} on {plan.platform["name"]}")')
    a('      (footprint ""))')
    cid_by_ref = {it["ref"]: it for it in plan.bom}
    for it in plan.bom:
        a(f'    (comp (ref "{it["ref"]}")')
        a(f'      (value "{it["name"]}")')
        a('      (footprint ""))')
    a('  )')
    a('  (nets')
    for code, net in enumerate(build_nets(plan), start=1):
        a(f'    (net (code "{code}") (name "{net.name}")')
        for pin in net.pins:
            ref = "MCU" if pin["ref"] == "MCU" else pin["ref"][:0] or pin["ref"]
            # ref for peripheral = its BOM ref when resolvable, else name slug
            a(f'      (node (ref "{_ref_for(plan, pin)}") (pin "{pin["pin"]}"))')
        a('    )')
    a('  )')
    a(')')
    return "\n".join(lines)


def _ref_for(plan, pin: dict[str, str]) -> str:
    if pin["ref"] == "MCU":
        return "MCU"
    for it in plan.bom:
        if it["name"] == pin["part"] or pin["part"].startswith(it["name"][:12]):
            return it["ref"]
    return pin["part"][:8].replace(" ", "_")


# ── design-rule checks ──────────────────────────────────────────────────────

@dataclass
class DrcItem:
    severity: str        # error | warning | info
    rule: str
    message: str
    suggestion: str = ""

    def to_dict(self): return asdict(self)


def run_drc(plan) -> list[DrcItem]:
    items: list[DrcItem] = []
    nets = build_nets(plan)
    net_map = {n.name: n for n in nets}
    comps = plan.components
    cids = {c["cid"] for c in comps}
    cats = {c["category"] for c in comps}
    has = lambda cid: cid in cids

    # 1. every plan needs a GND and a power net
    if "GND" not in net_map:
        items.append(DrcItem("error", "common ground", "No GND net found.",
                             "Tie every module ground together."))
    if not any(n in net_map for n in ("3V3", "5V")):
        items.append(DrcItem("error", "power rail", "No 3V3/5V rail net found.",
                             "Define a regulated rail and decouple each IC."))

    # 2. I2C pull-ups
    i2c_parts = [c for c in comps if "i2c" in c.get("protocols", [])]
    if i2c_parts and not has("i2c_pullups"):
        items.append(DrcItem("warning", "i2c pull-ups",
                             f"{len(i2c_parts)} I2C device(s) with no explicit 4.7kΩ pull-up pair.",
                             "Add 4.7kΩ from SDA and SCL to 3V3 unless the modules have onboard pull-ups."))
    if i2c_parts:
        items.append(DrcItem("info", "i2c addresses",
                             "Confirm unique I2C addresses with an i2cdetect/scan before stacking devices.",
                             "BME280=0x76/0x77, MPU6050=0x68, SSD1306=0x3C."))

    # 3. duplicate assignment of a non-shared net
    seen: dict[str, set[str]] = {}
    for net in nets:
        if net.name in RAIL_NET or net.name in SHARED_BUS_SIGNALS or net.name.startswith("CS") \
           or net.name in ("PWM",):
            continue
        for pin in net.pins:
            key = pin["pin"]
            seen.setdefault(net.name, set())
    # dedicated GPIO nets must each land on one MCU pin only
    mcu_pins = [p["pin"] for n in nets for p in n.pins if p["ref"] == "MCU"
                and n.name not in RAIL_NET and n.name not in SHARED_BUS_SIGNALS]
    if len(mcu_pins) != len(set(mcu_pins)):
        dups = {p for p in mcu_pins if mcu_pins.count(p) > 1}
        items.append(DrcItem("error", "pin conflict",
                             f"MCU pin(s) assigned to more than one dedicated signal: {sorted(dups)}.",
                             "Reassign one of the signals to a free GPIO."))

    # 4. logic level mismatch: a 5V-logic part on a 3.3V MCU without shifter
    vdd = plan.platform.get("power", {}).get("vdd", 3.3)
    five_volt = [c for c in comps if c.get("vcc", 3.3) and float(c.get("vcc", 3.3)) >= 5.0]
    if five_volt and vdd < 5.0 and not has("level_shifter"):
        items.append(DrcItem("warning", "logic level",
                             f"{', '.join(c['cid'] for c in five_volt)} expects 5V logic on a {vdd}V MCU.",
                             "Use a level shifter or 3.3V-compatible modules."))

    # 5. decoupling
    if not has("decoupling"):
        items.append(DrcItem("warning", "decoupling", "No decoupling capacitors in the BOM.",
                             "Add a 100nF ceramic across each IC VCC–GND."))

    # 6. motors need a driver / FET stage
    if "motor" in cats and "motordriver" not in cats:
        items.append(DrcItem("error", "motor drive",
                             "Motors are selected but no motor driver/FET stage is in the BOM.",
                             "Add a DRV8833/H-bridge or FET bank; never drive motors from GPIO directly."))

    # 7. current vs supply headroom
    peak = plan.power.get("estimated_peak_mA", 0)
    if peak:
        if peak > 800 and has("ams1117_3v3"):
            items.append(DrcItem("warning", "regulator headroom",
                                 f"Estimated {peak}mA exceeds an AMS1117 LDO's comfortable range (~800mA).",
                                 "Use a switching regulator (buck) or a higher-current LDO with heatsinking."))
        items.append(DrcItem("info", "power budget",
                             f"Estimated peak ≈ {peak}mA — measure on the bench; size supply with ≥30% margin.",
                             ""))

    # 8. radio certification
    if "radio" in cats or plan.platform_key in ("esp32_devkit", "raspberry_pi_sbc"):
        items.append(DrcItem("info", "rf certification",
                             "Intentional radios (Wi-Fi/BLE/2.4GHz) may need FCC/CE-RED for a product.", ""))

    return items


def cost_estimate(plan) -> dict[str, Any]:
    from trishula.engineering import components as C

    total = 0.0
    lines = []
    # platform board
    plat_price = C._PLATFORM_PRICE.get(plan.platform_key, 5.0)
    total += plat_price
    lines.append({"ref": "MCU", "name": plan.platform["name"], "qty": 1,
                  "unit": plat_price, "ext": round(plat_price, 2)})
    for c in plan.components:
        comp = C.CATALOGUE.get(c["cid"])
        unit = comp.price_usd if comp else 0.0
        qty = c.get("qty", 1)
        ext = round(unit * qty, 2)
        total += ext
        lines.append({"ref": "", "name": c["name"], "qty": qty,
                      "unit": round(unit, 2), "ext": ext})
    subtotal = round(total, 2)
    return {
        "currency": "USD",
        "subtotal": subtotal,
        "with_connectors": round(subtotal * 1.15, 2),
        "low_volume_unit_est": round(subtotal * 1.6, 2),
        "note": "rough hobbyist estimate from typical module prices; verify with current quotes",
        "lines": lines,
    }
