"""Test scaffolding & property generation (stdlib only).

Given changed source files, generate *deterministic* smoke tests plus
property-style skeletons for pure functions, so the verifier has something
new to exercise and the coding agent gets a starting point (a real model
fills in semantic assertions; the scaffolding at minimum proves imports work
and functions don't crash on edge inputs).

Output files are named ``test_trishula_autogen_<module>.py`` and clearly
marked as generated; the verifier includes them only for the current run and
they are safe to commit and extend.
"""

from __future__ import annotations

import ast
import json
from pathlib import Path
from typing import Dict, List

from trishula.core.logging import get_logger
from trishula.tools.workspace import Workspace

log = get_logger("coding.testgen")

_SAFE_DEFAULTS = {
    "int": "0",
    "float": "1.0",
    "str": '"x"',
    "bool": "False",
    "bytes": 'b"x"',
    "list": "[]",
    "dict": "{}",
    "set": "set()",
    "tuple": "()",
    "Optional": "None",
}

def _header(module: str, expected: List[str]) -> str:
    """Build the generated-file preamble. Uses string concat to avoid
    formatting braces that appear in the embedded code."""
    lines = [
        '"""AUTO-GENERATED by Trishula (verifier phase 2).',
        f"Smoke/property scaffolding for changed module {module!r}.",
        'Extend the TODO assertions with real expected values.',
        '"""',
        "",
        "import os, sys",
        "# Make the trishula package importable whether run from the repo or elsewhere.",
        "_tri_root = os.environ.get('TRISHULA_PYTHONPATH')",
        "if _tri_root and _tri_root not in sys.path:",
        "    sys.path.insert(0, _tri_root)",
        "try:",
        "    import trishula  # noqa: F401",
        "except ImportError:",
        "    # running inside the Shiva repo checkout itself: walk up to the",
        "    # directory that contains the trishula package.",
        "    _here = os.path.dirname(os.path.abspath(__file__))",
        "    for _up in range(4):",
        "        if os.path.isdir(os.path.join(_here, 'trishula')):",
        "            sys.path.insert(0, _here)",
        "            break",
        "        _here = os.path.dirname(_here)",
        "from trishula.coding.proplib import check, ints, floats, strs, lists, booleans  # noqa: F401",
        f"import {module} as _mod",
        "",
        "",
        "def test_module_imports_and_defines():",
        '    names = {n for n in dir(_mod) if not n.startswith("_")}',
        f"    assert {expected!r} <= names",
        "",
        "",
    ]
    return "\n".join(lines)


def _annotation_name(ann: ast.expr | None) -> str:
    if ann is None:
        return ""
    if isinstance(ann, ast.Name):
        return ann.id
    if isinstance(ann, ast.Subscript):
        return _annotation_name(ann.value)
    if isinstance(ann, ast.Constant):
        return str(ann.value)
    return ""


def _sample_expr(ann_name: str) -> str:
    return _SAFE_DEFAULTS.get(ann_name, "None")


def _is_pureish(fn: ast.FunctionDef) -> bool:
    """Heuristic: annotated, no obvious side-effect calls to outside."""
    side_effects = {"open", "input", "print", "write", "system", "subprocess"}
    for node in ast.walk(fn):
        if isinstance(node, ast.Call):
            func = node.func
            name = getattr(func, "id", getattr(func, "attr", ""))
            if name in side_effects:
                return False
    return any(a.annotation is not None for a in fn.args.args)


def extract_functions(source: str) -> List[dict]:
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    out: List[dict] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
            args = []
            for a in node.args.args:
                args.append((a.arg, _annotation_name(a.annotation)))
            ret = _annotation_name(node.returns)
            out.append({
                "name": node.name,
                "args": args,
                "return": ret,
                "pureish": _is_pureish(node),
            })
    return out


def module_name_for(relpath: str) -> str:
    p = Path(relpath).with_suffix("")
    return ".".join(p.parts)


def generate_tests(
    workspace: Workspace,
    changed_py_files: List[str],
    *,
    write: bool = True,
) -> Dict[str, str]:
    """Generate smoke/property test files for changed source modules.

    Returns ``{source_relpath: generated_test_relpath}`` for modules with at
    least one public, non-crashing function.
    """
    generated: Dict[str, str] = {}
    for rel in changed_py_files:
        if "test" in Path(rel).name:
            continue  # don't generate tests for tests
        try:
            source = workspace.read(rel)
        except OSError:
            continue
        funcs = extract_functions(source)
        if not funcs:
            continue
        module = module_name_for(rel)
        body = self_test_body(module, funcs)
        if not write:
            generated[rel] = body
            continue
        out_path = f"test_trishula_autogen_{Path(rel).stem}.py"
        workspace.write(out_path, body)
        generated[rel] = out_path
        log.info("generated %s for %s (%d public funcs)", out_path, rel, len(funcs))
    return generated


def self_test_body(module: str, funcs: List[dict]) -> str:
    expected = [f["name"] for f in funcs]
    blocks = [_header(module, expected)]
    for f in funcs:
        name = f["name"]
        args = f["args"]
        # Smoke test with edge-ish defaults: must not crash.
        call_args = []
        strategy_names = []
        for arg, ann in args:
            call_args.append(f"{arg}={_sample_expr(ann)}")
            strategy_names.append(_strategy_for(ann))
        call = f"_mod.{name}({', '.join(call_args)})"
        blocks.append(f"def test_{name}_smoke():\n")
        blocks.append("    # TODO: assert the expected result; currently ensures no crash on edge defaults\n")
        blocks.append(f"    try:\n        {call}\n    except TypeError:\n        pass  # signature needs richer fixtures — see property test below\n\n")
        # Property skeleton for pure annotated functions
        if f["pureish"] and args and all(ann in _SAFE_DEFAULTS for _, ann in args):
            strat = ", ".join(f"{arg}={_strategy_for(ann)}" for arg, ann in args)
            blocks.append(f"def test_{name}_property_determinism():\n")
            blocks.append("    # Property: repeated calls with the same input return equal results\n")
            blocks.append("    # (replace with the real invariant of this function).\n")
            blocks.append(
                "    check(lambda *a: _mod." + name + "(*a) == _mod." + name + "(*a), "
                + ", ".join(f"{_strategy_for(ann)}" for _, ann in args)
                + ", name='" + name + ".determinism', iterations=30)\n\n"
            )
    return "".join(blocks)


def _strategy_for(ann: str) -> str:
    return {
        "int": "ints(-50, 50)",
        "float": "floats(-1e3, 1e3)",
        "str": "strs(12)",
        "bool": "booleans()",
        "list": "lists(ints(-10, 10), 8)",
    }.get(ann, "booleans()")
